########################################################################
#                                                                      #
#                The WebServer for Minecraft Plugin                    #
#                                                                      #
########################################################################
#                                                                      #
# By using this plugin, you automatically accept Minecraft EULA!       #
# If you have any problem, you can ask on our Discord for Support in   #
# channel #📃┃help or by forum channel called #📈┃support. If you     #
# found any bug, please report it. It'll help you and for our plugin!  #
#                                                                      #
########################################################################
#          Created by: Radekminecraft    and    FungY911               #
########################################################################
#                                                                      #
#                                                                      #
#                   All Permissions for this plugin                    #
#                                                                      #
#              All Perms - ws.*                                        #
#              Webserver Start - ws.start                              #
#              Webserver Stop - ws.stop                                #
#              Plugin Reload - ws.reload                               #
#              Set new port - ws.port                                  #
#              Tab - ws.tab                                            #
#              Get Version of the Plugin - ws.ver                      #
#              Show Updates - ws.update                                #
#              Update variable in config - ws.set                      #
#                                                                      #
#                                                                      #
########################################################################
WebServer:
  port: 8080 # Set this to your open port.
  isRunning: false # Automatically run web on crash, if was started.
  domain: "CHANGE_ME" # Domain of your server, default is ip of your server.
  ssl: false # toggle: true/false, set this to true only if you have generated certificate and webserver pointed to domain.
  accessLog: true # toggle: true/false, acceslog from website.
  threads: 10 # Maximum number of threads, 0 for unlimited

No-Permission: "&cYou dont have permissions to do this command"
Version: "1.3.2" # Do not edit this line!
